MastersMVC2/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace MastersMVC2.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MastersMVC2/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace MastersMVC2.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MastersMVC2/Views/About/Index.cshtml
<div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
        <div class="header_top">
            <div class="container-fluid">
                <div class="contact_nav">
                    <a href="">
                        <i class="fa fa-phone" aria-hidden="true"></i>
                        <span>
                            Call : +01 123455678990
                        </span>
                    </a>
                    <a href="">
                        <i class="fa fa-envelope" aria-hidden="true"></i>
                        <span>
                            Email : demo@gmail.com
                        </span>
                    </a>
                </div>
            </div>
        </div>
        <div class="header_bottom">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-lg custom_nav-container ">
                    <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                        <span>
                            Inance
                        </span>
                    </a>

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class=""> </span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ">
                            <li class="nav-item active">
                                <a class="nav-link" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="About" asp-action="Index"> About</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Services" asp-action="Index">Services</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Contact" asp-action="Index">Contact Us</a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </header>
    <!-- end header section -->
</div>
<!-- about section -->

<section class="about_section layout_padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-md-6">
                <div class="detail-box">
                    <h2>
                        About us
                    </h2>
                    <p>
                        There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomisedThere are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised
                    </p>
                    <a href="">
                        Read More
                    </a>
                </div>
            </div>
            <div class="col-lg-7 col-md-6">
                <div class="img-box">
                    <img src="~/images/about-img.jpg" alt="">
                </div>
            </div>
        </div>
    </div>
</section>

<!-- end about section -->